source "https://rubygems.org"

ruby ">= 3.1"

# Rails API
gem "rails", "~> 7.2"
gem "puma", "~> 6.4"

# Elastic Email SDK
gem "ElasticEmail", "~> 4.2"

# Environment variables
gem "dotenv-rails", "~> 3.0"
